[package]
name = "stellarix-desktop"
version = "1.1.0"
edition = "2021"
description = "Десктоп-оболочка Stellarix на Tauri"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
name = "stellarix_desktop_lib"

[[bin]]
name = "stellarix-desktop_bin"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6", features = [] }

[dependencies]
tauri = { version = "2.11", features = [] }
tauri-plugin-opener = "2"
stellarix = { path = ".." }
audiodsp = { path = "../audiodsp" }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["chrono"] }
tracing-appender = "0.2"
chrono = "0.4.45"
sha2 = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
ndk = "0.9"
ndk-context = "0.1"
jni = "0.21"
cpal = "0.18"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(not(target_os = "android"))'.dependencies]
cpal = "0.18"

[workspace]

[profile.dev.package.rustfft]
opt-level = 3

[profile.dev.package.realfft]
opt-level = 3

[profile.dev.package.audiodsp]
opt-level = 3
