#!/bin/sh
set -eu

ENV_FILE="/app/.env"

if [ ! -f "$ENV_FILE" ]; then
  : "${DATABASE_URL:?DATABASE_URL is required}"
  : "${USERNAME_SECRET:?USERNAME_SECRET is required}"
  : "${SESSION_SECRET:?SESSION_SECRET is required}"

  cat > "$ENV_FILE" <<EOF
USERNAME_SECRET=${USERNAME_SECRET}
SESSION_SECRET=${SESSION_SECRET}
DATABASE_URL=${DATABASE_URL}
APP_ENVIRONMENT=${APP_ENVIRONMENT:-production}
LOG_LEVEL=${LOG_LEVEL:-info}
EOF
fi

exec "$@"
